export const START_FETCHING_PIZZA_DATA = 'START_FETCHING_PIZZA_DATA';
export const SUCCESS_FETCHING_PIZZA_DATA = 'SUCCESS_FETCHING_PIZZA_DATA';
export const ERROR_FETCHING_PIZZA_DATA = 'ERROR_FETCHING_PIZZA_DATA';

export const START_FETCHING_TOP_ORDERS = 'START_FETCHING_TOP_ORDERS';
export const SUCCESS_FETCHING_TOP_ORDERS = 'SUCCESS_FETCHING_TOP_ORDERS';
export const ERROR_FETCHING_TOP_ORDERS = 'ERROR_FETCHING_TOP_ORDERS';

export const SELECT_TOP_PIZZA_ORDER = 'SELECT_TOP_PIZZA_ORDER';
export const INCREASE_SELECT_TOP_PIZZA_ORDER =
  'INCREASE_SELECT_TOP_PIZZA_ORDER';
export const DECREASE_SELECT_TOP_PIZZA_ORDER =
  'DECREASE_SELECT_TOP_PIZZA_ORDER';

export const START_FETCHING_FEEDBACK = 'START_FETCHING_FEEDBACK';
export const SUCCESS_FETCHING_FEEDBACK = 'SUCCESS_FETCHING_FEEDBACK';
export const ERROR_FETCHING_FEEDBACK = 'ERROR_FETCHING_FEEDBACK';
